/* Generated by CLex */

typedef enum TokenType
{
	TokenType_CLex_Reject,
	TokenType_LeftParenthesis,
	TokenType_RightParenthesis,
	TokenType_LeftBrace,
	TokenType_RightBrace,
	TokenType_Semicolon,
	TokenType_KeywordInt,
	TokenType_KeywordReturn,
	TokenType_Number,
	TokenType_Identifier,
	TokenType_Comment,
	TokenType_Whitespace
} TokenType;

TokenType CLex(const char **input);