#include "dfa.h"
#include "hash_table.h"

void PrintDFAState(DFAState *state, size_t index)
{
	printf("State %zu: %p\n\tsymbol: %s\n", index, state, state->symbol);
	for (int c = 0; c < DFASTATE_EDGES_MAX; ++c)
	{
		if (state->edges[c])
		{
			printf("\t%c: %p\n", c, state->edges[c]);
		}
	}
}

void WriteDFAState(const DFAState *state, HashTable *stateToIndex, FILE *output)
{
	fprintf(output, "\t{");
	if (state->symbol)
	{
		fprintf(output, "\"%s\", {", state->symbol);
	}
	else
	{
		fprintf(output, "NULL, {");
	}
	
	bool first = true;
	for (int i = 0; i < DFASTATE_EDGES_MAX; ++i)
	{
		if (state->edges[i])
		{
			if (first)
			{
				fprintf(output, ", ");
			}
			fprintf(output, "[%i] = %zu", i, (size_t)*HashTable_Find(stateToIndex, state->edges[i]));
		}
	}
	
	fprintf(output, "}}");
}

static size_t DFA_HashDFAState(const void *data)
{
	return (size_t)data * 2654435761;
}
static bool DFA_CompareDFAState(const void *lhs, const void *rhs)
{
	return lhs == rhs;
}
void WriteDFA(const DFA *dfa, const DFAState *state, FILE *output)
{
	HashTable stateToIndex;
	HashTable_Create(&stateToIndex, dfa->states.size + dfa->states.size / 2, 1.0f, DFA_HashDFAState, DFA_CompareDFAState);
	
	for (size_t i = 0; i < dfa->states.size; ++i)
	{
		HashTable_Insert(&stateToIndex, Vector_Get(&dfa->states, i), (void *)(i + 1));
	}
	
	const char *header = "/* Generated by CLex */\
\
typedef struct State State;\
struct State\
{\
	const char *symbol;\
	size_t edges[128];\
};\
\
static State states[%i] =\
{\
	{NULL},\
";
	fprintf(output, header);
	for (size_t i = 0; i < dfa->states.size; ++i)
	{
		if (i != 0)
		{
			fprintf(output, ",\n");
		}
		WriteDFAState(Vector_Get(&dfa->states, i), &stateToIndex, output);
	}
	const char *footer = "\n};";
	fprintf(output, footer);
	
	HashTable_Destroy(&stateToIndex);
}

int main(int argc, char **argv)
{
	NFA nfa;
	NFA_Create(&nfa);
	
	DFAEntry entries[2];
	entries[0].symbol = "IfStatement";
	entries[1].symbol = "IfelseStatement";
	NFA_ParseRegex(&nfa, "if", &entries[0].expression);
	NFA_ParseRegex(&nfa, "ifelse", &entries[1].expression);
	
	DFA dfa;
	DFA_Create(&dfa);
	DFAState *start = DFA_FromEntries(&dfa, entries, 2);
	start = DFA_Minimize(&dfa, start);
	
	FILE *output;
	fopen_s(&output, "output.clex.c", "wb");
	
	WriteDFA(&dfa, start, output);
	
	fclose(output);
	printf("Start at %p\n", start);
	for (size_t i = 0; i < dfa.states.size; ++i)
	{
		PrintDFAState(Vector_Get(&dfa.states, i), i);
	}
	
	DFA_Destroy(&dfa);
	NFA_Destroy(&nfa);
	
	return 0;
}