#include "codegen.h"

#include "hash_table.h"

#include <stdio.h>

void Codegen_WriteHeader(FILE *output, const char **symbols, size_t symbolsSize)
{
	fprintf(output, "/* Generated by CLex */\n\ntypedef enum TokenType\n{\n\tTokenType_CLex_Reject");
	for (size_t i = 0; i < symbolsSize; ++i)
	{
		fprintf(output, ",\n\tTokenType_%s", symbols[i]);
	}
	fprintf(output, "\n} TokenType;\n\nTokenType CLex(const char **input);");
}
static void Codegen_WriteDFAState(FILE *output, const DFAState *state, HashTable *stateToIndex)
{
	fprintf(output, "\t{");
	if (state->symbol)
	{
		fprintf(output, "TokenType_%s, {[0] = 0", state->symbol);
	}
	else
	{
		fprintf(output, "TokenType_CLex_Reject, {[0] = 0");
	}
	
	bool first = true;
	for (int i = 0; i < DFASTATE_EDGES_MAX; ++i)
	{
		if (state->edges[i])
		{
			fprintf(output, ", [%i] = %zu", i, (size_t)*HashTable_Find(stateToIndex, state->edges[i]));
			first = false;
		}
	}
	
	fprintf(output, "}}");
}
static size_t DFA_HashDFAState(const void *data)
{
	return (size_t)data * 2654435761;
}
static bool DFA_CompareDFAState(const void *lhs, const void *rhs)
{
	return lhs == rhs;
}
void Codegen_WriteSource(FILE *output, const DFA *dfa, const DFAState *start, const char *outputHeaderPath)
{
	HashTable stateToIndex;
	HashTable_Create(&stateToIndex, dfa->states.size + dfa->states.size / 2, 1.0f, DFA_HashDFAState, DFA_CompareDFAState);
	
	for (size_t i = 0; i < dfa->states.size; ++i)
	{
		HashTable_Insert(&stateToIndex, Vector_Get(&dfa->states, i), (void *)(i + 1));
	}
	
	const char *header = "/* Generated by CLex */\n\
\n\
#include \"%s\"\n\
\n\
typedef struct State State;\n\
struct State\n\
{\n\
	TokenType type;\n\
	size_t edges[128];\n\
};\n\
\n\
static const State k_states[] =\n\
{\n\
	{TokenType_CLex_Reject, {[0] = 0}},\n\
";
	fprintf(output, header, outputHeaderPath);
	for (size_t i = 0; i < dfa->states.size; ++i)
	{
		if (i != 0)
		{
			fprintf(output, ",\n");
		}
		Codegen_WriteDFAState(output, Vector_Get(&dfa->states, i), &stateToIndex);
	}
	const char *footer = "\n};\n";
	fprintf(output, footer);
	
	fprintf(output, "\nstatic const size_t k_initialState = %zu;\n", (size_t)*HashTable_Find(&stateToIndex, start));
	
	const char *clexDefinition = "\n\
TokenType CLex(const char **input)\n\
{\n\
	size_t lastState = k_initialState;\n\
	size_t state = k_states[lastState].edges[**input];\n\
	while (state)\n\
	{\n\
		++*input;\n\
		lastState = state;\n\
		state = k_states[lastState].edges[**input];\n\
	}\n\
	return k_states[lastState].type;\n\
}";
	fprintf(output, clexDefinition);
	
	HashTable_Destroy(&stateToIndex);
}